### ISSUE TITLE
Add a license file so others can use (or not use) this project

### ISSUE THREAD

**Issue by mrjones-plip** [juztcode/pr-updater#3]
Heya! Love this little action and was considering forking it for a project of mine.  However, it's unlicensed, and thus [all rights reserved](https://softwareengineering.stackexchange.com/a/276147).  Could you add a license (hopefully an [OSS](https://choosealicense.com/) one!) so others might benefit from this?

**Comment by randilfernando** [comment]
To make this action truly open source MIT license added. Cheers!!

**Comment by mrjones-plip** [comment]
Wonderful - thank you :heart:
